import argparse

parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=234, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=14, type=int)

parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='C:/Myoung_Chul_KIM/VadCLIP(AAAI_2024)/VadCLIP-main/model/model_ucf.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='model/checkpoint.pth')
parser.add_argument('--batch-size', default=64, type=int)
parser.add_argument('--train-list', default='list/ucf_CLIP_rgb.csv')
parser.add_argument('--test-list', default='list/ucf_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='list/gt_ucf.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment_ucf.npy')
parser.add_argument('--gt-label-path', default='list/gt_label_ucf.npy')
parser.add_argument('--video-path', type=str, help="Path to video frames directory")
parser.add_argument('--test-mode', type=str, choices=['test', 'Category_test', 'test_real_time', 'plot_score', 'gt_distribution'], required=True, help="Select test mode: 'test' or 'test_real_time'")
parser.add_argument('--video-save-path', type=str, help="Path to save video file directory")
parser.add_argument('--score-video-save-path', type=str, help="Path to save video file directory")
parser.add_argument('--gt-split-save-path', type=str, help="Path to save splited GT file directory")
parser.add_argument('--category-gt-dir', type=str, help="Category GT file directory")
parser.add_argument('--annotation-path', type=str, help="GT annotation txt file directory")

parser.add_argument('--lr', default=2e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[4, 8])